version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: npm start
    networks:
      - zbank
  mongodb:
    image: mongo
    ports:
      - '27019:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - zbank

volumes:
  mongodb_data:

networks:
  zbank:
    external: true  
